name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: [bug]
assignees:
- TheMoksej
issue_body: false
body:
- type: markdown
  attributes:
    value: |
      Thanks for taking the time to fill out this bug report!
- type: input
  attributes:
    label: Contact Details
    description: How can we get in touch with you if we need more info?
    placeholder: ex. email@example.com, user#1234
  validations:
    required: false
- type: textarea
  attributes:
    label: What Happened?
    description: Also tell us how can we reproduce the bug?
    value: |
      1.
      2.
      ....
  validations:
    required: true
- type: checkboxes
  attributes:
    label: Code of Conduct
    description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com)
    options:
    - label: I agree to follow this project's Code of Conduct
      required: true
